theme: minima
title: Appl3Tree
author: Tree
description: This GitHub Page is used for compiling my notes on material studied throughout my journey in cybersecurity as a whole. Because my interests jump fairly regularly, I expect this to cover a wide variety of fields.
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      category: ignore
